"""Fig. 10: ESD-only representative-window ablation.

Reads the Stage-1 ablation CSV generated by sweep_deadband_phase1_windows.py
with wind/PV deadbands fixed at 36 mHz and only ESD deadband varied.
Output: fig10_esd_ablation.pdf/.png
"""
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

from fig_style import COLORS, apply_style, polish_axes, save_figure

HERE = Path(__file__).parent
ROOT = HERE.parent.parent.parent
SUMMARY_CSV = ROOT / "results" / "ablation_esd_only_stage1_20260503" / "phase1_combo_ranked.csv"
OUT_PDF = HERE / "fig10_esd_ablation.pdf"


def main() -> None:
    df = pd.read_csv(SUMMARY_CSV).copy()
    if df.empty:
        raise RuntimeError(f"No rows in {SUMMARY_CSV}")
    df = df.sort_values("esd_deadband_hz")

    x = df["esd_deadband_hz"] * 1000.0
    edge = df["edge_mass_36"] * 100.0
    share36 = df["share_abs_gt_0p036"] * 100.0
    tail = df["share_abs_gt_0p05"] * 100.0
    effort = df["esd_throughput"]

    apply_style()
    fig, (ax_top, ax_bot) = plt.subplots(
        2, 1, figsize=(3.5, 2.9), sharex=True,
        gridspec_kw={"height_ratios": (1.0, 1.0), "hspace": 0.14},
    )
    ax_effort = ax_bot.twinx()

    ax_top.plot(x, share36, marker="o", markersize=3.7, linewidth=1.1,
                color=COLORS["teal"], label=r"$|\Delta f|>36$ mHz")
    ax_top.plot(x, edge, marker="s", markersize=3.4, linewidth=1.0,
                color=COLORS["blue"], label=r"$\mathrm{EM}_{36}$")
    ax_bot.plot(x, tail, marker="o", markersize=3.6, linewidth=1.1,
                color=COLORS["red"], label=r"$|\Delta f|>50$ mHz")
    ax_effort.plot(x, effort, marker="^", markersize=3.7, linewidth=1.0,
                   color=COLORS["amber"], label=r"$E_{\mathrm{ESD}}$")

    for ax in (ax_top, ax_bot):
        ax.axvline(15.0, color=COLORS["ink"], linestyle=(0, (2, 2)),
                   linewidth=0.65, alpha=0.72)
        ax.set_xlim(float(x.min()) - 1.8, float(x.max()) + 5.0)
        polish_axes(ax)

    ax_top.annotate("selected", xy=(15.0, 0.98), xycoords=("data", "axes fraction"),
                    xytext=(3, -2), textcoords="offset points",
                    ha="left", va="top", fontsize=6.3, color=COLORS["ink"])

    ax_top.set_ylabel("boundary risk (%)")
    ax_bot.set_ylabel("tail risk (%)")
    ax_effort.set_ylabel(r"$E_{\mathrm{ESD}}$ (p.u.$\cdot$s)")
    ax_bot.set_xlabel(r"ESD deadband $d_{\mathrm{b,ESD}}$ (mHz), wind/PV = 36 mHz")
    ax_bot.set_xticks(list(x))

    ax_effort.spines["top"].set_visible(False)
    ax_effort.spines["right"].set_color(COLORS["amber"])
    ax_effort.spines["right"].set_linewidth(0.7)
    ax_effort.tick_params(colors=COLORS["amber"], width=0.6, length=2.6, labelsize=7)
    ax_effort.yaxis.label.set_color(COLORS["amber"])
    ax_bot.tick_params(axis="y", colors=COLORS["red"])
    ax_bot.yaxis.label.set_color(COLORS["red"])

    label_kwargs = dict(textcoords="offset points", xytext=(4, 0),
                        ha="left", va="center", fontsize=6.4)
    ax_top.annotate(r"$|\Delta f|>36$ mHz", (x.iloc[-1], share36.iloc[-1]),
                    color=COLORS["teal"], **label_kwargs)
    ax_top.annotate(r"$\mathrm{EM}_{36}$", (x.iloc[-1], edge.iloc[-1]),
                    color=COLORS["blue"], **label_kwargs)
    ax_bot.annotate(r"$|\Delta f|>50$ mHz", (x.iloc[-2], tail.iloc[-2]),
                    textcoords="offset points", xytext=(4, -4),
                    ha="left", va="top", fontsize=6.4,
                    color=COLORS["red"])
    ax_effort.annotate(r"$E_{\mathrm{ESD}}$", (x.iloc[-1], effort.iloc[-1]),
                       textcoords="offset points", xytext=(-4, 4),
                       ha="right", va="bottom", fontsize=6.4,
                       color=COLORS["amber"])

    save_figure(fig, OUT_PDF)


if __name__ == "__main__":
    main()
